baseURL: https://hossainnotes.netlify.app
languageCode: en-us
title: My Notes

# Needed for mermaid/katex shortcodes
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
